#!/bin/bash
set -euo pipefail

DIR=${1:-"."}
FILES=$(find-unignored-files "${DIR}" ".+\\.py$")

if [[ -z "${FILES}" ]]; then
  exit 0
fi

echo "${FILES}" | xargs ruff check --config="${LINT_CONFIG_PATH}"/.ruff.toml
