#!/bin/bash
set -euo pipefail

DIR=${1:-"."}
FILES=$(find-unignored-files "${DIR}" "\\(^\\|.*\\/\\)Dockerfile$")

if [[ -z "${FILES}" ]]; then
  exit 0
fi

echo "${FILES}" | xargs hadolint --config "${LINT_CONFIG_PATH}"/.hadolint.yaml
