---
name: Publishes the docker image on DockerHub.

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish the images that have changed.
        run: |
          FILES=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${GITHUB_SHA})
          readarray -t FILES_ARRAY <<< "$FILES"
          IFS='/'
          DOCKER_IMAGES=()

          for FILENAME in "${FILES_ARRAY[@]}"; do
            if [[ "$FILENAME" != *"/"* ]]; then
              continue
            fi
            if [[ "$FILENAME" == "."* ]]; then
              continue
            fi

            read -a PATHS <<< "$FILENAME"
            DOCKER_IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${PATHS[0]}:${PATHS[1]}"
            if [[ " ${DOCKER_IMAGES[@]} " =~ " ${DOCKER_IMAGE_NAME} " ]]; then
              continue
            fi

            docker build -t "${DOCKER_IMAGE_NAME}" ${PATHS[0]}/${PATHS[1]}/
            docker push "${DOCKER_IMAGE_NAME}"
            DOCKER_IMAGES+=($DOCKER_IMAGE_NAME)
          done
